(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STOPS=[['🏠','Casa de Jacó'],['🌾','Campo'],['🐪','Viagem'],['🏡','Potifar'],['🔒','Prisão'],['🏛️','Palácio']];
const COLORS={red:{name:'Vermelho',hex:'#d9293e'},blue:{name:'Azul',hex:'#1769c2'},yellow:{name:'Amarelo',hex:'#ffd538'},green:{name:'Verde',hex:'#239447'}};
const THEMES=['Casa de Jacó','Campo dos irmãos','Viagem ao Egito','Casa de Potifar','Prisão','Palácio de Faraó'];
const SAVE='joseGameV301',VERSION=301,LIMIT=60,SPIN_MS=15000;let timerId=null,audioCtx=null,wheelRotation=0,childRotation=0,rouletteId=null,rouletteAudio=[],rouletteTickTimer=null,rouletteActive=false,musicTimer=null,musicStep=0,selectionBusy=false;
const state={mode:'individual',count:15,players:[],children:[],childOrder:[],childCursor:0,currentChild:null,turn:0,questions:[],index:0,streak:0,lives:3,correct:0,answered:false,choiceMode:false,sound:true,seconds:LIMIT,paused:false,selectionMode:'wheel',manualTheme:null};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function themeOf(q){if(Number.isInteger(q.theme)&&q.theme>=0&&q.theme<THEMES.length)return q.theme;const n=q.id;if(n<=10||(n>=46&&n<=50))return 0;if((n>=11&&n<=16)||(n>=51&&n<=56)||n===58||n===59)return 1;if(n===17||n===18||n===57||n===60)return 2;if((n>=19&&n<=22)||(n>=61&&n<=66))return 3;if((n>=23&&n<=30)||(n>=67&&n<=76))return 4;return 5}
function screens(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0)}
function tone(freq=440,d=.05,gain=.025){if(!state.sound||(rouletteActive&&gain<=.02))return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.frequency.value=freq;const loud=Math.min(.48,gain*4);g.gain.setValueAtTime(loud,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.start();o.stop(audioCtx.currentTime+d)}catch(e){}}
function musicNote(freq,d=.28,volume=.065,type='triangle'){if(!state.sound||!audioCtx)return;const now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain(),filter=audioCtx.createBiquadFilter();o.type=type;o.frequency.value=freq;filter.type='lowpass';filter.frequency.value=type==='square'?1050:1750;o.connect(filter);filter.connect(g);g.connect(audioCtx.destination);g.gain.setValueAtTime(rouletteActive?volume*.42:volume,now);g.gain.exponentialRampToValueAtTime(.001,now+d);o.start(now);o.stop(now+d)}
function musicDrum(accent=false){if(!state.sound||!audioCtx)return;const now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(accent?145:105,now);o.frequency.exponentialRampToValueAtTime(44,now+.16);g.gain.setValueAtTime(rouletteActive?.035:accent?.115:.075,now);g.gain.exponentialRampToValueAtTime(.001,now+.19);o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+.2);if(musicStep%2){const length=Math.floor(audioCtx.sampleRate*.055),buffer=audioCtx.createBuffer(1,length,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const n=audioCtx.createBufferSource(),ng=audioCtx.createGain(),hp=audioCtx.createBiquadFilter();n.buffer=buffer;hp.type='highpass';hp.frequency.value=3200;ng.gain.value=rouletteActive?.018:.052;n.connect(hp);hp.connect(ng);ng.connect(audioCtx.destination);n.start(now)}}
function musicPulse(){if(!state.sound){musicTimer=null;return}audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const melody=[294,311,370,392,440,392,370,311,294,370,440,466,440,392,370,311],bass=[147,147,131,131,155,155,147,147],i=musicStep%melody.length;musicNote(melody[i],.31,.074,i%4===3?'square':'triangle');if(musicStep%2===0)musicNote(bass[Math.floor(musicStep/2)%bass.length],.48,.052,'sine');if(musicStep%4===0)musicNote(melody[i]*1.5,.22,.038,'triangle');musicDrum(musicStep%4===0);musicStep++;musicTimer=setTimeout(musicPulse,330)}
function startMusic(){if(!state.sound||musicTimer)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume().then(musicPulse)}catch(e){}}
function stopMusic(){clearTimeout(musicTimer);musicTimer=null}
function updateSoundButtons(){const label=state.sound?'🔊 Ligado':'🔇 Desligado';$('#soundToggle').classList.toggle('on',state.sound);$('#soundToggle').setAttribute('aria-pressed',state.sound);$('#soundToggle').textContent=label;$('#musicWheelToggle').textContent=state.sound?'🎵 Música ligada':'🔇 Música desligada'}
function beep(type='tap'){const s={tap:[440,.05,.025],tick:[620,.04,.018],ok:[784,.18,.08],bad:[180,.25,.07],start:[523,.15,.06]}[type];tone(...s)}
function stopRouletteAudio(){clearTimeout(rouletteTickTimer);rouletteActive=false;rouletteAudio.forEach(n=>{try{n.stop?.();n.disconnect?.()}catch(e){}});rouletteAudio=[]}
function rouletteClick(accent=false){if(!state.sound||!audioCtx)return;const now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.setValueAtTime(accent?980:720,now);o.frequency.exponentialRampToValueAtTime(accent?420:260,now+.055);g.gain.setValueAtTime(accent?.46:.34,now);g.gain.exponentialRampToValueAtTime(.001,now+.065);o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+.07);rouletteAudio.push(o,g)}
function startRouletteAudio(){if(!state.sound)return;audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume().then(()=>{stopRouletteAudio();rouletteActive=true;const start=performance.now();const step=()=>{const elapsed=performance.now()-start;if(elapsed>=15000){rouletteClick(true);setTimeout(()=>rouletteClick(true),220);setTimeout(stopRouletteAudio,500);return}rouletteClick(false);let interval;if(elapsed<2200)interval=240-175*(elapsed/2200);else if(elapsed<7600)interval=65;else{const p=(elapsed-7600)/7400;interval=65+520*p*p}rouletteTickTimer=setTimeout(step,interval)};step()})}
function victoryFx(){const fx=document.createElement('div');fx.className='celebration-fx';const colors=['#ef233c','#ffca3a','#1d70b7','#20b9b0','#8c55c8','#f36f56','#239447'];for(let i=0;i<90;i++){const c=document.createElement('i');c.className='confetti-piece';c.style.left=Math.random()*100+'vw';c.style.background=colors[i%colors.length];c.style.setProperty('--dur',(2.1+Math.random()*1.8)+'s');c.style.setProperty('--delay',(Math.random()*.55)+'s');c.style.setProperty('--drift',(-100+Math.random()*200)+'px');c.style.setProperty('--rot',(Math.random()*360)+'deg');fx.appendChild(c)}const word=document.createElement('div');word.className='victory-burst';word.textContent='PARABÉNS!';fx.appendChild(word);document.body.appendChild(fx);[523,659,784,1047].forEach((n,i)=>setTimeout(()=>tone(n,.28,.09),i*150));setTimeout(()=>fx.remove(),4000)}
function wrongFx(){const fx=document.createElement('div');fx.className='bomb-fx';fx.innerHTML='<div class="blast-ring"></div><div class="boom-word">BOOM!</div>';for(let i=0;i<18;i++){const s=document.createElement('i');s.className='smoke';s.style.setProperty('--size',(80+Math.random()*180)+'px');s.style.setProperty('--x',(15+Math.random()*70)+'%');s.style.setProperty('--y',(35+Math.random()*35)+'%');s.style.setProperty('--dx',(-180+Math.random()*360)+'px');fx.appendChild(s)}document.body.classList.add('screen-shake');document.body.appendChild(fx);tone(90,.8,.16);setTimeout(()=>tone(55,1.2,.12),180);setTimeout(()=>document.body.classList.remove('screen-shake'),600);setTimeout(()=>fx.remove(),2900)}
function names(){if(state.mode==='teams'){$('#names').innerHTML='<fieldset><legend>Escolha de 2 a 4 equipes</legend><div class="team-selector">'+Object.entries(COLORS).map(([key,c])=>`<label class="team-check team-${key}"><input type="checkbox" data-team="${key}" checked>${c.name}</label>`).join('')+'</div></fieldset>'}else $('#names').innerHTML='<div class="individual-ready">👤 <b>Modo individual</b><span>Não é necessário cadastrar nomes. Toque em começar e vá direto à seleção dos temas.</span></div>'}
$$('.pick').forEach(b=>b.addEventListener('click',()=>{beep();const g=b.dataset.group;$$(`[data-group="${g}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state[g]=g==='count'?+b.dataset.value:b.dataset.value;if(g==='mode')names()}));
function makePlayers(){if(state.mode==='teams'){const chosen=$$('[data-team]:checked').map(x=>x.dataset.team);if(chosen.length<2){alert('Escolha pelo menos duas equipes.');return null}return chosen.map(color=>({name:'Equipe '+COLORS[color].name,color,score:0,correct:0}))}return[{name:'Jogador individual',color:'blue',score:0,correct:0}]}
function prepareJourney(){Object.assign(state,{children:state.mode==='teams'?state.children:[],childOrder:state.mode==='teams'?shuffle(state.children.map((_,i)=>i)):[],childCursor:0,currentChild:null,turn:0,index:0,streak:0,lives:3,correct:0,answered:false,choiceMode:false,seconds:LIMIT,paused:false,manualTheme:null});state.questions=shuffle(QUESTIONS).slice(0,Math.min(state.count,QUESTIONS.length));save();screens('game');renderMap();startMusic();showWheel();beep('start')}
function openRegistration(){const players=makePlayers();if(!players)return;state.players=players;if(state.mode==='individual'){state.children=[];prepareJourney();return}$('#childrenFields').innerHTML=players.map((p,i)=>`<div class="children-card team-${p.color}"><label>${p.name}</label><textarea data-children="${i}" placeholder="Um nome por linha&#10;Ana&#10;Pedro&#10;Lucas"></textarea></div>`).join('');$$('[data-children]').forEach(t=>t.addEventListener('input',countChildren));countChildren();screens('registration')}
function countChildren(){const total=$$('[data-children]').reduce((n,t)=>n+t.value.split(/\n/).map(x=>x.trim()).filter(Boolean).length,0);$('#childrenTotal').textContent=total}
function confirmChildren(){const children=[];$$('[data-children]').forEach(t=>{const playerIndex=+t.dataset.children;t.value.split(/\n/).map(x=>x.trim()).filter(Boolean).forEach(name=>children.push({name:name.slice(0,32),playerIndex}))});if(children.length<2){alert('Cadastre pelo menos duas crianças para jogar em equipes.');return}state.children=children;prepareJourney()}
function renderMap(){const pct=state.questions.length?Math.min(100,state.index/state.questions.length*100):0,current=Math.min(5,Math.floor(pct/20));$('#map').innerHTML=STOPS.map((s,i)=>`<div class="stop ${i<current?'done':''} ${i===current?'current':''}"><span>${s[0]}</span>${s[1]}</div>`).join('');$('#trackFill').style.width=pct+'%';$('#joseMarker').style.left=pct+'%';$('#joseMarker').textContent=pct>82?'🧑🏽‍💼':'🧒🏽'}
function nextChildIndex(){if(state.childCursor>=state.childOrder.length){state.childOrder=shuffle(state.children.map((_,i)=>i));state.childCursor=0}return state.childOrder[state.childCursor++]}
function childCandidates(winnerIndex){const others=shuffle(state.children.map((_,i)=>i).filter(i=>i!==winnerIndex)),seg=360/state.children.length,k=Math.max(0,Math.min(others.length,Math.round(22.5/seg-.5)));others.splice(k,0,winnerIndex);return{list:others,winnerSlot:0}}
function renderChildWheel(list){const n=list.length,seg=360/n,size=n<=20?'1rem':n<=50?'.62rem':'.42rem';$('#childWheel').style.background=`conic-gradient(${list.map((idx,i)=>{const color=COLORS[state.players[state.children[idx].playerIndex].color].hex;return`${color} ${i*seg}deg ${(i+1)*seg}deg`}).join(',')})`;$('#childLabels').innerHTML=list.map((idx,i)=>{const deg=(i+.5)*seg,a=deg*Math.PI/180,x=50+29*Math.sin(a),y=50-29*Math.cos(a),name=state.children[idx].name,rotation=deg>180?deg+90:deg-90;return`<span class="child-name" style="left:${x}%;top:${y}%;--name-size:${size};transform:translate(-50%,-50%) rotate(${rotation}deg)">${name.replace(/[<>&]/g,'')}</span>`}).join('')}
function auditNames(){const used=new Set(state.childOrder.slice(0,state.childCursor));$('#auditCount').textContent=state.children.length;$('#auditNames').innerHTML=state.children.map((c,i)=>`<span class="audit-name ${used.has(i)?'drawn':''} ${state.currentChild===c?'current':''}">${c.name} • ${state.players[c.playerIndex].name}</span>`).join('')}
function remainingThemes(){const counts=Array(THEMES.length).fill(0);for(let i=state.index;i<state.questions.length;i++)counts[themeOf(state.questions[i])]++;return counts}
function renderManualThemes(){const counts=remainingThemes();$$('[data-manual-theme]').forEach(button=>{const theme=+button.dataset.manualTheme,count=counts[theme];button.disabled=count===0;button.classList.toggle('selected',state.manualTheme===theme);button.setAttribute('aria-pressed',state.manualTheme===theme);button.querySelector('small').textContent=count?`${count} ${count===1?'pergunta disponível':'perguntas disponíveis'}`:'Sem perguntas nesta partida'})}
function applySelectionMode(){const team=state.mode==='teams',manual=state.selectionMode==='manual',dual=$('.dual-wheels');$('#wheelModeBtn').classList.toggle('selected',!manual);$('#wheelModeBtn').setAttribute('aria-pressed',!manual);$('#manualModeBtn').classList.toggle('selected',manual);$('#manualModeBtn').setAttribute('aria-pressed',manual);$('#manualThemes').classList.toggle('hidden',!manual);$('#journeyWheelBlock').classList.toggle('hidden',manual);$('#childWheelBlock').classList.toggle('hidden',!team);dual.classList.toggle('hidden',manual&&!team);dual.classList.toggle('single-wheel',!team||manual);$('#wheelTitle').textContent=manual?(team?'Escolha a trajetória + participante':'Escolha a trajetória'):(team?'Trajetória + participante':'Roleta das trajetórias');renderManualThemes();const ready=!manual||Number.isInteger(state.manualTheme);$('#spinBtn').disabled=!ready;$('#spinBtn').textContent=manual?(team?'Sortear participante nesta trajetória 🎡':'Confirmar trajetória e continuar ▶'):(team?'Girar as duas roletas 🎡':'Girar a roleta dos temas 🎡')}
function setSelectionMode(mode){if(selectionBusy)return;state.selectionMode=mode;state.manualTheme=null;applySelectionMode();save();beep()}
function showWheel(){const team=state.mode==='teams';selectionBusy=false;state.manualTheme=null;$('#wheelResult').textContent='';$('#childResult').textContent='';$('#wheelResult').classList.remove('winner');$('#childResult').classList.remove('winner');$('#editParticipants').classList.toggle('hidden',!team);$('#auditPanel').classList.toggle('hidden',!team);$('#auditToggle').classList.toggle('hidden',!team);if(team){renderChildWheel(state.children.map((_,i)=>i));auditNames()}applySelectionMode();$('#wheelScreen').classList.add('show');tone(440,.12,.08)}
function chooseQuestion(theme){const candidates=[];for(let i=state.index;i<state.questions.length;i++)if(themeOf(state.questions[i])===theme)candidates.push(i);if(!candidates.length)return false;const pick=candidates[Math.floor(Math.random()*candidates.length)];[state.questions[state.index],state.questions[pick]]=[state.questions[pick],state.questions[state.index]];return true}
function spin(){const team=state.mode==='teams',manual=state.selectionMode==='manual',available=[...new Set(state.questions.slice(state.index).map(themeOf))],theme=manual?state.manualTheme:available[Math.floor(Math.random()*available.length)];if(!Number.isInteger(theme)||!available.includes(theme)){alert('Escolha uma trajetória que ainda tenha perguntas disponíveis.');renderManualThemes();return}selectionBusy=true;let winnerIndex=null,draw=null;if(team){winnerIndex=nextChildIndex();draw=childCandidates(winnerIndex);renderChildWheel(draw.list)}if(!manual){const center=theme*60+30,desired=(360-center)%360,current=((wheelRotation%360)+360)%360,delta=(desired-current+360)%360;wheelRotation+=3600+delta;$$('#wheel .wheel-label').forEach(x=>x.style.transform='translate(-50%,-50%)');$('#wheel').style.transform=`rotate(${wheelRotation}deg)`}if(team){const childCenter=draw.winnerSlot*(360/draw.list.length)+(180/draw.list.length),childDesired=(360-childCenter)%360,childCurrent=((childRotation%360)+360)%360,childDelta=(childDesired-childCurrent+360)%360;childRotation+=3960+childDelta;$('#childWheel').style.transform=`rotate(${childRotation}deg)`}$('#spinBtn').disabled=true;$('#spinBtn').textContent=manual?(team?'A criança está sendo sorteada...':'Preparando a trajetória...'):(team?'As roletas estão girando...':'A trajetória está sendo sorteada...');const animated=!manual||team;if(animated){let ticks=0;clearInterval(rouletteId);rouletteId=setInterval(()=>{const progress=ticks++/120;tone(300+(ticks%9)*35,.025,.016);if(progress>.75){clearInterval(rouletteId);rouletteId=setInterval(()=>tone(350+(ticks++%5)*45,.035,.018),190)}},110)}const wait=animated?SPIN_MS:350;setTimeout(()=>{clearInterval(rouletteId);tone(880,.45,.1);if(!manual)$$('#wheel .wheel-label').forEach(x=>x.style.transform=`translate(-50%,-50%) rotate(${-wheelRotation}deg)`);if(!chooseQuestion(theme)){selectionBusy=false;applySelectionMode();return}if(team){state.currentChild=state.children[winnerIndex];state.turn=state.currentChild.playerIndex;const p=state.players[state.turn];$('#childResult').textContent=`🎉 ${state.currentChild.name} — ${p.name}`;$('#childResult').classList.add('winner')}else{state.currentChild=null;state.turn=0}$('#wheelResult').textContent='📖 '+THEMES[theme];$('#wheelResult').classList.add('winner');setTimeout(()=>{$('#wheelScreen').classList.remove('show');renderQuestion();save()},animated?1500:450)},wait)}
function startTimer(reset=true){clearInterval(timerId);if(reset)state.seconds=LIMIT;state.paused=false;$('#pauseBtn').textContent='⏸';paintTimer();timerId=setInterval(()=>{state.seconds--;paintTimer();if(state.seconds<=5&&state.seconds>0)beep('tick');if(state.seconds<=0){clearInterval(timerId);if(!state.answered)resolve(false,state.choiceMode,'Tempo encerrado!')}},1000)}
function paintTimer(){const n=Math.max(0,state.seconds);$('#timer').textContent=n;$('#timerFill').style.width=(n/LIMIT*100)+'%';$('.timer-box').classList.toggle('urgent',n<=5)}
function togglePause(){if(state.answered||!$('#directJudge').classList.contains('hidden'))return;if(state.paused){document.querySelector('.paused-overlay')?.remove();startTimer(false)}else{state.paused=true;clearInterval(timerId);$('#pauseBtn').textContent='▶';const d=document.createElement('div');d.className='paused-overlay';d.innerHTML='<div><h2>Jogo pausado</h2><p>O cronômetro está parado.</p><button class="primary">Continuar ▶</button></div>';d.querySelector('button').onclick=togglePause;document.body.appendChild(d)}beep()}
function renderQuestion(){state.answered=false;state.choiceMode=false;const q=state.questions[state.index],p=state.players[state.turn],card=$('.question-card'),scene=['casa-jaco','campo-irmaos','viagem-egito','casa-potifar','prisao','palacio-farao'][themeOf(q)];card.className='question-card team-'+p.color+' scene-card';$('#game').style.setProperty('--game-scene',`url("${scene}.png")`);$('#game').dataset.scene=scene;$('#turnName').textContent=state.mode==='teams'?`${state.currentChild?.name||p.name} • ${p.name}`:'Jogador individual';$('.game-head').style.borderBottom='7px solid '+COLORS[p.color].hex;$('#counter').textContent=`Pergunta ${state.index+1} de ${state.questions.length}`;$('#stars').textContent='⭐'.repeat(state.lives)+'☆'.repeat(3-state.lives);$('#score').textContent=p.score;$('#streak').textContent=state.streak;$('#stageTag').textContent=THEMES[themeOf(q)];$('#question').textContent=q.q;$('#instruction').textContent=state.mode==='teams'?'A criança responde por 100 pontos. Se precisar, sua equipe pode ajudar usando as alternativas por 50 pontos.':'Responda sem opções por 100 pontos ou veja as alternativas por 50 pontos.';$('#decision').classList.remove('hidden');$('#directJudge').classList.add('hidden');$('#answers').classList.add('hidden');$('#answers').innerHTML='';startTimer()}
function direct(){if(state.answered)return;clearInterval(timerId);beep();const q=state.questions[state.index];$('#decision').classList.add('hidden');$('#directJudge').classList.remove('hidden');$('#correctText').textContent=q.options[q.correct];$('#instruction').textContent='O professor confere a resposta falada e registra o resultado.'}
function showChoices(){if(state.answered)return;state.choiceMode=true;beep();$('#decision').classList.add('hidden');$('#answers').classList.remove('hidden');$('#instruction').textContent='A equipe pode ajudar. Esta questão vale 50 pontos.';const q=state.questions[state.index],opts=shuffle(q.options.map((text,i)=>({text,ok:i===q.correct})));opts.forEach((o,i)=>{const b=document.createElement('button');b.className='answer';b.innerHTML=`<span class="letter">${'ABCD'[i]}</span><span></span>`;b.lastChild.textContent=o.text;b.addEventListener('click',()=>resolve(o.ok,true));$('#answers').appendChild(b)})}
function resolve(ok,choice,reason=''){if(state.answered)return;state.answered=true;clearInterval(timerId);const q=state.questions[state.index],p=state.players[state.turn],value=choice?50:100;if(ok){p.score+=value;p.correct++;state.correct++;state.streak++;victoryFx();$('#feedbackIcon').textContent='🌟';$('#feedbackTitle').textContent=choice?'Equipe ajudou: 50 pontos!':'Resposta individual: 100 pontos!'}else{state.streak=0;state.lives=Math.max(0,state.lives-1);wrongFx();if(state.mode==='teams'){const other=state.players[(state.turn+1)%state.players.length];other.score+=value;$('#feedbackTitle').textContent=`${value} pontos para ${other.name}`}else{p.score-=value;$('#feedbackTitle').textContent=`Penalidade de ${value} pontos`}$('#feedbackIcon').textContent=state.lives?'💛':'🌈'}$('#explanation').textContent=(reason?reason+' ':'')+(ok?`Valeu ${value} pontos. `:`A resposta correta era “${q.options[q.correct]}”. `)+q.explanation;$('#reference').textContent='📖 '+q.ref;$('#feedback').classList.add('show');renderMap();save()}
function next(){beep();$('#feedback').classList.remove('show');state.index++;if(state.index>=state.questions.length)return finish();renderMap();showWheel();save()}
function finish(){clearInterval(timerId);stopMusic();localStorage.removeItem(SAVE);screens('result');const name=state.players.map(p=>p.name).join(', '),total=state.players.reduce((a,p)=>a+p.score,0);$('#certificateName').textContent=name;$('#finalScore').textContent=state.mode==='teams'?total:state.players[0].score;$('#resultText').textContent=`A jornada chegou ao palácio: ${state.correct} de ${state.questions.length} respostas corretas.`;$('#teamScores').innerHTML=state.mode==='teams'?state.players.map(p=>`<div class="team-row team-${p.color}"><span>${p.name}</span><span>${p.score} pontos • ${p.correct} acertos</span></div>`).join(''):''}
function save(){localStorage.setItem(SAVE,JSON.stringify({...state,version:VERSION}));$('#continue').classList.remove('hidden')}
function resume(){try{const s=JSON.parse(localStorage.getItem(SAVE));if(!s||s.version!==VERSION||!s.questions?.length||(s.mode==='teams'&&!s.children?.length))throw 0;Object.assign(state,s);screens('game');renderMap();startMusic();renderQuestion()}catch(e){localStorage.removeItem(SAVE);$('#continue').classList.add('hidden')}}
function editParticipants(){$('#wheelScreen').classList.remove('show');$('#childrenFields').innerHTML=state.players.map((p,i)=>`<div class="children-card team-${p.color}"><label>${p.name}</label><textarea data-children="${i}">${state.children.filter(c=>c.playerIndex===i).map(c=>c.name).join('\n')}</textarea></div>`).join('');$$('[data-children]').forEach(t=>t.addEventListener('input',countChildren));countChildren();screens('registration')}
function restartGame(){if(!confirm('Reiniciar o jogo e zerar toda a pontuação?'))return;clearInterval(timerId);clearInterval(rouletteId);stopMusic();localStorage.removeItem(SAVE);$('#wheelScreen').classList.remove('show');$('#continue').classList.add('hidden');screens('home')}
function testSound(){state.sound=true;$('#soundToggle').classList.add('on');$('#soundToggle').textContent='🔊 Ligado';[392,523,659,784,1047].forEach((n,i)=>setTimeout(()=>tone(n,.35,.14),i*180))}
let awaitingOfficialStart=false;
const officialButton=document.createElement('button');officialButton.id='startOfficialBtn';officialButton.className='primary official-start hidden';officialButton.textContent='▶ Começar pergunta oficialmente';document.querySelector('.audit-panel').before(officialButton);
const showWheelCore=showWheel,renderQuestionCore=renderQuestion,wrongFxCore=wrongFx;
showWheel=function(){awaitingOfficialStart=true;officialButton.classList.add('hidden');showWheelCore()};
renderQuestion=function(){if(awaitingOfficialStart){$('#wheelScreen').classList.add('show');officialButton.classList.remove('hidden');return}renderQuestionCore()};
function laserSound(){if(!state.sound)return;audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume().then(()=>{const now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(1800,now);o.frequency.exponentialRampToValueAtTime(85,now+.75);g.gain.setValueAtTime(.42,now);g.gain.exponentialRampToValueAtTime(.001,now+.8);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(now+.82)})}
wrongFx=function(){laserSound();wrongFxCore();setTimeout(()=>{$('#feedbackIcon').innerHTML='<img class="feedback-church-logo" src="logo-igreja.png" alt="Logotipo da igreja">'},0)};
officialButton.addEventListener('click',()=>{awaitingOfficialStart=false;officialButton.classList.add('hidden');$('#wheelScreen').classList.remove('show');renderQuestionCore();tone(660,.18,.12)});
$('#editParticipants').addEventListener('click',editParticipants);$('#restartNow').addEventListener('click',restartGame);$('#testSound').addEventListener('click',testSound);$('#spinBtn').addEventListener('pointerdown',()=>{if(state.selectionMode==='wheel'||state.mode==='teams')startRouletteAudio()});
$('#wheelModeBtn').addEventListener('click',()=>setSelectionMode('wheel'));$('#manualModeBtn').addEventListener('click',()=>setSelectionMode('manual'));$$('[data-manual-theme]').forEach(button=>button.addEventListener('click',()=>{if(selectionBusy||button.disabled)return;state.manualTheme=+button.dataset.manualTheme;renderManualThemes();$('#spinBtn').disabled=false;$('#spinBtn').textContent=state.mode==='teams'?'Sortear participante nesta trajetória 🎡':'Confirmar trajetória e continuar ▶';save();beep()}));
$('#auditToggle').addEventListener('click',()=>{const panel=$('#auditPanel'),open=!panel.classList.toggle('audit-hidden');$('#auditToggle').textContent=open?'👁 Esconder auditoria':'👁 Mostrar auditoria'});
$('#musicWheelToggle').addEventListener('click',()=>{state.sound=!state.sound;if(state.sound)startMusic();else stopMusic();updateSoundButtons();save()});
async function toggleFullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen()}else if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen()}else if(document.documentElement.webkitRequestFullscreen){document.documentElement.webkitRequestFullscreen()}}catch(e){}$('#fullscreenBtn').textContent=document.fullscreenElement?'↙️ Sair da tela cheia':'📺 Tela cheia / Projetor'}
$('#fullscreenBtn').addEventListener('click',toggleFullscreen);document.addEventListener('fullscreenchange',()=>{$('#fullscreenBtn').textContent=document.fullscreenElement?'↙️ Sair da tela cheia':'📺 Tela cheia / Projetor'});
function toggleWheelPanel(panelId,buttonId){const panel=$('#'+panelId),button=$('#'+buttonId),willOpen=panel.classList.contains('hidden');$$('.wheel-tab-panel').forEach(p=>p.classList.add('hidden'));$$('.wheel-tabs button').forEach(b=>b.setAttribute('aria-expanded','false'));if(willOpen){panel.classList.remove('hidden');button.setAttribute('aria-expanded','true')}}
$('#instructionsTab').addEventListener('click',()=>toggleWheelPanel('instructionsPanel','instructionsTab'));$('#configTab').addEventListener('click',()=>toggleWheelPanel('configPanel','configTab'));$$('[data-close-panel]').forEach(b=>b.addEventListener('click',()=>{b.parentElement.classList.add('hidden');$$('.wheel-tabs button').forEach(x=>x.setAttribute('aria-expanded','false'))}));
$('#start').addEventListener('click',openRegistration);$('#registrationBack').addEventListener('click',()=>screens('home'));$('#confirmChildren').addEventListener('click',confirmChildren);$('#continue').addEventListener('click',resume);$('#spinBtn').addEventListener('click',spin);$('#pauseBtn').addEventListener('click',togglePause);$('#next').addEventListener('click',next);$('#directAnswer').addEventListener('click',direct);$('#showChoices').addEventListener('click',showChoices);$('#directCorrect').addEventListener('click',()=>resolve(true,false));$('#directWrong').addEventListener('click',()=>resolve(false,false));$('#restart').addEventListener('click',()=>{stopMusic();screens('home')});$('#print').addEventListener('click',()=>print());$('#homeBtn').addEventListener('click',()=>{clearInterval(timerId);if(confirm('Voltar à configuração? A partida ficará salva.')){stopMusic();screens('home')}else startTimer(false)});$('#soundToggle').addEventListener('click',()=>{state.sound=!state.sound;if(state.sound){beep();startMusic()}else stopMusic();updateSoundButtons()});
$('#bankCount').textContent=QUESTIONS.length+' perguntas';if(localStorage.getItem(SAVE))$('#continue').classList.remove('hidden');renderMap();updateSoundButtons();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw-v300.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{}));
})();
